// -----------------------------------------------------------------------------
// App.tsx
// CV web page (HTML) + a "Download PDF" button that DOWNLOADS a .pdf file
// directly (one click, no dialog). The PDF is generated by ResumePdf.tsx with
// @react-pdf/renderer: real selectable text (ATS-friendly) and the same design
// shown on the web.
// -----------------------------------------------------------------------------
import { useState } from "react";
import { pdf } from "@react-pdf/renderer";
import Resume from "./web/Resume";
import ResumePdf from "./pdf/ResumePdf";
import resumeData from "./data";

const fileName = `CV-${resumeData.personalInfo.name.replace(/\s+/g, "-")}.pdf`;

export default function App() {
  const [loading, setLoading] = useState(false);

  async function handleDownload() {
    if (loading) return;
    setLoading(true);
    try {
      const blob = await pdf(<ResumePdf />).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="app">
      <div className="toolbar no-print">
        <button className="btn" onClick={handleDownload} disabled={loading}>
          {loading ? "Generating PDF…" : "Download PDF"}
        </button>
      </div>

      <div className="sheet-wrap">
        <Resume />
      </div>
    </div>
  );
}
